### ISSUE TITLE
Shortcut.HotkeyAlreadyBoundException

### ISSUE THREAD

**Issue by core01** [Anc813/MicMute#1]
Hi, thank you for the app, it is very actual now, because of pandemic and mass online communications where you should know muted or not muted your mic at the moment.

I'm very exiced about this app, I switched off from Lenovo T480s to HP and I miss lenovo built-in mic mute & indication, your app replaced it well.

Periodically when I shutting down or reloading my PC I get exception, described below.

Also I added MicMute.exe to StartUp, and after this exception hotkey for toggle mute are resets.

Hope you could help me.

Windows 10, version 1909 (OS Build 18363.836)

![image](https://user-images.githubusercontent.com/2903772/82117865-f119e880-977b-11ea-8232-d97854c65b24.png)

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Shortcut.HotkeyAlreadyBoundException (0x80004005): This hotkey cannot be bound because it has been previously bound either by this application or another running application.
   at Shortcut.HotkeyContainer.Add(Hotkey hotkey, HotkeyCallback callback)
   at Shortcut.HotkeyBinder.Bind(Hotkey hotkeyCombo)
   at MicMute.MainForm.MainForm_FormClosing(Object sender, FormClosingEventArgs e)
   at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e)
   at System.Windows.Forms.Form.WmClose(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MicMute
    Assembly Version: 0.0.3.0
    Win32 Version: 0.0.3.0
    CodeBase: file:///C:/Users/user/MicMute.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AudioSwitcher.AudioApi.CoreAudio
    Assembly Version: 4.0.0.308
    Win32 Version: 0.0.3.0
    CodeBase: file:///C:/Users/user/MicMute.exe
----------------------------------------
AudioSwitcher.AudioApi
    Assembly Version: 4.0.0.308
    Win32 Version: 0.0.3.0
    CodeBase: file:///C:/Users/user/MicMute.exe
----------------------------------------
Shortcut
    Assembly Version: 1.0.0.0
    Win32 Version: 0.0.3.0
    CodeBase: file:///C:/Users/user/MicMute.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Reactive.Core
    Assembly Version: 3.0.1000.0
    Win32 Version: 0.0.3.0
    CodeBase: file:///C:/Users/user/MicMute.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by Anc813** [comment]
@core01 hope I have fixed this. Please [try new version](https://github.com/Anc813/MicMute/releases/tag/0.0.4)

**Comment by core01** [comment]
@Anc813 Thank you for helping, I will reopen issue if the problem remains!
