### ISSUE TITLE
.NET Unhandled Exception after Windows update

### ISSUE THREAD

**Issue by jhawkins002** [Anc813/MicMute#38]
Running MicMute on Windows 10 here, and after the latest update the app crashes upon use with a .NET unhandled exception. Happy to include the output of the error below:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at MicMute.MainForm.<ToggleMicStatus>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4614.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
MicMute
    Assembly Version: 0.0.8.0
    Win32 Version: 0.0.8.0
    CodeBase: file:///C:/Users/jhawk/Downloads/MicMute.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4550.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
AudioSwitcher.AudioApi.CoreAudio
    Assembly Version: 4.0.0.308
    Win32 Version: 0.0.8.0
    CodeBase: file:///C:/Users/jhawk/Downloads/MicMute.exe
----------------------------------------
AudioSwitcher.AudioApi
    Assembly Version: 4.0.0.308
    Win32 Version: 0.0.8.0
    CodeBase: file:///C:/Users/jhawk/Downloads/MicMute.exe
----------------------------------------
Shortcut
    Assembly Version: 1.0.0.0
    Win32 Version: 0.0.8.0
    CodeBase: file:///C:/Users/jhawk/Downloads/MicMute.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4605.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Reactive.Core
    Assembly Version: 3.0.1000.0
    Win32 Version: 0.0.8.0
    CodeBase: file:///C:/Users/jhawk/Downloads/MicMute.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

**Comment by jhawkins002** [comment]
Ok so now out of the blue I cannot seem to replicate this - so Im closing. Sorry for the spam haha.
